# Generated by Django 2.0.3 on 2018-03-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0002_auto_20180318_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='none.png', upload_to=''),
        ),
    ]
