# Generated by Django 2.0.3 on 2018-03-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0004_auto_20180320_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
