# Generated by Django 2.0.3 on 2018-03-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0006_auto_20180320_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_is_followed', to='hangout.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
    ]
