# Generated by Django 2.0.3 on 2018-03-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0007_auto_20180320_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='follower',
            new_name='profile',
        ),
    ]
