# Generated by Django 2.0.3 on 2018-03-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0009_auto_20180320_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='who_follows', to='hangout.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followers',
            name='me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='who_is_followedd', to='hangout.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_is_followed', to='hangout.Profile'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_followss', to='hangout.Profile'),
        ),
    ]
